### ISSUE TITLE
Plugin not compatible with newest (2023.2) Intellij

### ISSUE THREAD

**Issue by rrjjvv** [earthly/earthly-intellij-plugin#12]
![image](https://github.com/earthly/earthly-intellij-plugin/assets/4579303/9b9c564d-7597-43f5-af1f-e6c75fafbf8f)

Intellij details:
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 25, 2023

**Comment by oderwat** [comment]
I also miss a working version.

**Comment by rrjjvv** [comment]
It is trivial to create a private (working) copy until a proper release is published.  You just need to change
https://github.com/earthly/earthly-intellij-plugin/blob/main/build.gradle.kts#L37
to reflect the new version.  IOW,
```diff
diff --git a/build.gradle.kts b/build.gradle.kts
index b548926..a19561a 100644
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -34,7 +34,7 @@ tasks {
 
     patchPluginXml {
         sinceBuild.set("212")
-        untilBuild.set("231.*")
+        untilBuild.set("232.*")
     }
 
     signPlugin {
```
then build the plugin (`earthly +dist`, which will generate a local zip file), then use that file and do "install plugin from file".

**Comment by Velutas** [comment]
Reopening until version is released

**Comment by Velutas** [comment]
New version 0.0.6 is now released
