### ISSUE TITLE
Add back support for PhpStorm

### ISSUE THREAD

**Issue by EamonKeane** [earthly/earthly-intellij-plugin#18]
I noticed the conversation here potentially saying that the inclusion of PHP was causing issues with other languages. I guess it was removed, it would be nice to have it back if it wasn't too much work.

https://github.com/earthly/earthly-intellij-plugin/issues/9

**Comment by idelvall** [comment]
Thanks @EamonKeane we will try to include it in the next release

**Comment by idelvall** [comment]
Just released [version 0.0.7](https://plugins.jetbrains.com/plugin/20392-earthly/versions/stable) supporting for PhpStorm
