### ISSUE TITLE
Highlighting breaks if there's a comment in the middle of a command

### ISSUE THREAD

**Issue by tim-silico** [earthly/earthly-intellij-plugin#3]
Thanks for the posting this plugin, it's great to have highlighting.

There seems to be an issue if there's a comment in the middle of a command, where the comment isn't highlighted the same as others, and the second section of the command gets the red squiggles.

![image](https://user-images.githubusercontent.com/106956336/201651266-c8f31b25-0871-4187-9f20-2caa79281dec.png)

**Comment by felpeyu** [comment]
Thanks for reporting @tim-silico

**Comment by felpeyu** [comment]
This would have been funny :)
![image](https://user-images.githubusercontent.com/114394155/202284833-b7f71adf-6a32-43ff-8188-60be52f3d38b.png)

**Comment by felpeyu** [comment]
Fixed in https://plugins.jetbrains.com/plugin/20392-earthly/versions/stable/258476 !

**Comment by tim-silico** [comment]
Thank you.
