### ISSUE TITLE
Update needed?

### ISSUE THREAD

**Issue by oderwat** [earthly/earthly-intellij-plugin#32]
I am sure you got this but in GoLand (IntelliJ) the plugin says it is not compatible to the current release of the IDE.

> Build #GO-241.14494.238, built on March 28, 2024

<img width="342" alt="image" src="https://github.com/earthly/earthly-intellij-plugin/assets/719156/39b5258a-9e42-4b07-876c-151bfc502253">

**Comment by shalugin** [comment]
<img width="734" alt="image" src="https://github.com/earthly/earthly-intellij-plugin/assets/1784377/20fc1501-2c09-499e-a9c7-0382efc2cf4c">

**Comment by shalugin** [comment]
It looks like this has already been fixed in the `main` branch. I rebuilt the plugin form sources and installed it without errors.

**Comment by idelvall** [comment]
We've just published plugin [version 0.0.8](https://plugins.jetbrains.com/plugin/20392-earthly/edit/versions/stable/520002).

**Comment by shalugin** [comment]
@idelvall thanks!
