### ISSUE TITLE
Plugin shows errors on "flags"

### ISSUE THREAD

**Issue by ingwarsw** [earthly/earthly-intellij-plugin#4]
If there are extra flags on `VERSION` then plugin shows it as error.
See image below.
Without flags it shows as ok.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/5390156/202694856-32938a39-6166-4ae1-b4c1-8338163342c1.png">

**Comment by felpeyu** [comment]
fixed in https://plugins.jetbrains.com/plugin/20392-earthly/versions/stable/258476
