### ISSUE TITLE
No support for `TRY` `FINALLY`

### ISSUE THREAD

**Issue by ingwarsw** [earthly/earthly-intellij-plugin#5]
`TRY` `FINALLY` is not supported and shown as errors.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/5390156/202695184-5df01d0e-4cef-4d32-85a0-cfcc4673829a.png">

**Comment by idelvall** [comment]
Fixed in `0.0.4-x`  https://plugins.jetbrains.com/plugin/20392-earthly/versions
